### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by uki00a** [denolib/typeorm#2]
## TODO

- [ ] setup GitHub actions
- [x] replace `sqlite3` with `deno-sqlite`
  - #5 (unstable)
- [ ] replace `mysql` with `deno-mysql`
- [ ] replace `pg` with `deno-postgres`
- [ ] replace `redis` with `deno-redis`
- [ ] replace `mocha` and `chai` with `deno_std`
- [ ] replace `sinon` with some mocking library for deno

## Design goals

- API compatibility with typeorm (as much as possible)
- Does not depend on npm packages

## Merging patches from upstream TypeORM

TODO

## How to run tests

TODO

```sh
$  deno run --allow-read --allow-write --config ./tsconfig.json ./test/integration/sample1-simple-entity.ts
```

#### Decorator metadata is not supported

Deno only supports `esnext` as a compilation target, but typeorm assumes `es5`. Therefore, it is unpossible to avoid a problem about a cyclic reference between entities.

#### `@TransactionRepository` is not supported

This decorator depends on decorator metadata.

#### `@Column`

TODO

## Required permissions

|driver|read|write|net|env|plugin|
|:---:|:---:|:---:|:---:|:---:|:---:|
|sqlite| :heavy_check_mark: | :heavy_check_mark: ||||
